# Generated by Django 2.0.3 on 2018-03-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='name')),
                ('age', models.SmallIntegerField(verbose_name='age')),
                ('birth', models.DateField(blank=True, verbose_name='birthday')),
            ],
        ),
    ]
